[[drone]]
id = 1
connected_node_ids = [2, 6, 12, 15]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 3, 7, 11, 15]
pdr = 0.03

[[drone]]
id = 3
connected_node_ids = [2, 4, 8, 11]
pdr = 0.14

[[drone]]
id = 4
connected_node_ids = [3, 5, 9, 16]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [4, 10, 14]
pdr = 0.03

[[drone]]
id = 6
connected_node_ids = [1, 7, 16]
pdr = 0.14

[[drone]]
id = 7
connected_node_ids = [2, 6, 8, 13]
pdr = 0.05

[[drone]]
id = 8
connected_node_ids = [3, 7, 9, 17]
pdr = 0.03

[[drone]]
id = 9
connected_node_ids = [4, 8, 10, 13]
pdr = 0.14

[[drone]]
id = 10
connected_node_ids = [5, 9, 14, 17]
pdr = 0.05

[[client]]
id = 11
connected_drone_ids = [3, 2]

[[client]]
id = 12
connected_drone_ids = [1]

[[client]]
id = 13
connected_drone_ids = [9, 7]

[[client]]
id = 14
connected_drone_ids = [5, 10]

[[server]]
id = 15
connected_drone_ids = [1, 2]

[[server]]
id = 16
connected_drone_ids = [4, 6]

[[server]]
id = 17
connected_drone_ids = [8, 10]
