[[drone]]
id = 1
connected_node_ids = [2, 12, 15, 16, 17]
pdr = 0.0

[[drone]]
id = 2
connected_node_ids = [1, 11, 15, 16, 17]
pdr = 0.0

[[client]]
id = 11
connected_drone_ids = [1]

[[client]]
id = 12
connected_drone_ids = [2]

[[server]]
id = 15
connected_drone_ids = [1, 2]

[[server]]
id = 16
connected_drone_ids = [1, 2]

[[server]]
id = 17
connected_drone_ids = [1, 2]
