[[drone]]
id = 1
connected_node_ids = [2, 6]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 3, 7]
pdr = 0.03

[[drone]]
id = 3
connected_node_ids = [2, 4, 8]
pdr = 0.14

[[drone]]
id = 4
connected_node_ids = [3, 5, 9]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [4, 10]
pdr = 0.03

[[drone]]
id = 6
connected_node_ids = [1, 7]
pdr = 0.14

[[drone]]
id = 7
connected_node_ids = [2, 6, 8]
pdr = 0.05

[[drone]]
id = 8
connected_node_ids = [3, 7, 9]
pdr = 0.03

[[drone]]
id = 9
connected_node_ids = [4, 8, 10]
pdr = 0.14

[[drone]]
id = 10
connected_node_ids = [5, 9]
pdr = 0.05

[[client]]
id = 4
connected_drone_ids = [3, 2]

[[client]]
id = 5
connected_drone_ids = [1]

[[server]]
id = 6
connected_drone_ids = [2, 3]
